Updated GSOC Page
KamandPrompt/kamandprompt.github.io pull request #86
Opened 2019-07-01 08:46 UTC by fiterace

solves #83 please review and merge @abhigyank

2019-07-01 13:31 UTC, Varunvaruns9 requested changes
I've suggested some minor changes otherwise it looks good to me.

2019-07-01 13:31 UTC, Varunvaruns9 commented on gsoc/index.html
> +          <a href="https://www.facebook.com/vsvipul555?ref=br_rs" class="fab fa-facebook-f social-button"></a>
Remove `?ref=br_rs`.

2019-07-01 13:31 UTC, Varunvaruns9 commented on gsoc/index.html
> +          <a href="https://www.facebook.com/dheeraj.168?ref=br_rs" class="fab fa-facebook-f social-button"></a>
From here also.

2019-07-01 13:31 UTC, Varunvaruns9 commented on gsoc/index.html
> +          <a href="https://www.facebook.com/prajjwal.jha?ref=br_rs" class="fab fa-facebook-f social-button"></a>
And here.

2019-07-01 13:31 UTC, Varunvaruns9 commented on gsoc/index.html
> +          <p>(Contract) PHPMYADMIN</p>
Write Contract in all caps like MENTOR.

2019-07-01 13:31 UTC, Varunvaruns9 commented on gsoc/index.html
> +          <p>LABLUAPUCRIO</p>
PUCRIO is the name of the university. Just keep LABLUA.

2019-07-02 17:02 UTC, fiterace commented
@Varunvaruns9 I have made the suggested changes. please review and merge.

2019-07-02 18:10 UTC, Varunvaruns9 commented
@abhigyank.

2019-07-03 00:45 UTC, merged